version: '3.6'
services:
  nginx-front:
    image: nginx:1.17.8
    ports:
      - 80:80
    volumes:
    - ./code-website:/code
    - ./docker/new-configuration-nginx.conf:/etc/nginx/conf.d/new-configuration-nginx.conf


        